In [1]:
import cv2

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Convolution2D,MaxPooling2D,ZeroPadding2D
from tensorflow.keras.layers import Dense, Flatten, BatchNormalization, Dropout,Softmax, Activation
from tensorflow.keras.preprocessing.image import load_img,img_to_array
import tensorflow.keras.backend as k


In [3]:
from keras.applications.vgg16 import preprocess_input


Using TensorFlow backend.


In [4]:
import warnings
warnings.filterwarnings('ignore')
import os

In [5]:
#Define VGG Model Architecture
model = Sequential()
model.add(ZeroPadding2D((1,1),input_shape=(224,224,3)))
model.add(Convolution2D(64,(3,3),activation = 'relu'))
model.add(ZeroPadding2D((1,1)))
model.add(Convolution2D(64,(3,3),activation = 'relu'))
model.add(MaxPooling2D((2,2),strides = (2,2)))
model.add(ZeroPadding2D((1,1)))
model.add(Convolution2D(128, (3, 3), activation='relu'))
model.add(ZeroPadding2D((1,1)))
model.add(Convolution2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2,2), strides=(2,2)))
model.add(ZeroPadding2D((1,1)))
model.add(Convolution2D(256, (3, 3), activation='relu'))
model.add(ZeroPadding2D((1,1)))
model.add(Convolution2D(256, (3, 3), activation='relu'))
model.add(ZeroPadding2D((1,1)))
model.add(Convolution2D(256, (3, 3), activation='relu'))
model.add(MaxPooling2D((2,2), strides=(2,2)))
model.add(ZeroPadding2D((1,1)))
model.add(Convolution2D(512, (3, 3), activation='relu'))
model.add(ZeroPadding2D((1,1)))
model.add(Convolution2D(512, (3, 3), activation='relu'))
model.add(ZeroPadding2D((1,1)))
model.add(Convolution2D(512, (3, 3), activation='relu'))
model.add(MaxPooling2D((2,2), strides=(2,2)))
model.add(ZeroPadding2D((1,1)))
model.add(Convolution2D(512, (3, 3), activation='relu'))
model.add(ZeroPadding2D((1,1)))
model.add(Convolution2D(512, (3, 3), activation='relu'))
model.add(ZeroPadding2D((1,1)))
model.add(Convolution2D(512, (3, 3), activation='relu'))
model.add(MaxPooling2D((2,2), strides=(2,2)))
model.add(Convolution2D(4096, (7, 7), activation='relu'))
model.add(Dropout(0.5))
model.add(Convolution2D(4096, (1, 1), activation='relu'))
model.add(Dropout(0.5))
model.add(Convolution2D(2622, (1, 1)))
model.add(Flatten())
model.add(Activation('softmax'))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [6]:
model.load_weights("D:\\opencv\\vgg_face_weights.h5")

In [7]:
os.chdir("D:\\opencv\\training\\cell")
base_dir = os.getcwd()
base_dir

'D:\\opencv\\training\\cell'

In [8]:
vgg_out= Model(inputs=model.layers[0].input, outputs=model.layers[-2].output)

In [9]:
from mtcnn.mtcnn import MTCNN
detector = MTCNN()
import warnings
warnings.filterwarnings('ignore')

In [13]:
#First we need to collect images of ourselves to train the mode

def webcam(folder, sub):
    vs= cv2.VideoCapture(0)
    count = 0
    while True:
        check,frame = vs.read()
        count = count+1
        result = detector.detect_faces(frame)
        for i in range(len(result)):
            (startx,starty,endx,endy) = (result[i]['box'][0],result[i]['box'][1],
                                         result[i]['box'][0]+result[i]['box'][2],result[i]['box'][1]+result[i]['box'][3])
            confidence = result[i]['confidence']
            if (confidence > 0.5):
                cv2.rectangle(frame,(startx,starty),(endx,endy),(0,255,0),3)
                if not os.path.exists(base_dir+'\\'+folder):
                    print('New Directory Created')
                    os.makedirs(base_dir+'\\'+folder)
                if not os.path.exists(base_dir+'\\'+folder+'\\'+sub):
                    print('New Directory Created')
                    os.makedirs(base_dir+'\\'+folder+'\\'+sub)
                updated_face_path = base_dir+'\\'+folder+'\\'+sub
                if (starty >=0) and (endy>=0) and (startx>=0) and (endx>=0):
                    frame_face = frame[starty:endy,startx:endx]
                    #resizing the image as VGG model requires evry image to be 224*224
                    frame_face = cv2.resize(frame_face,(224,224))
                    print((startx,starty,endx,endy))
                    try:
                        cv2.imwrite(updated_face_path+'\\'+str(count)+str(i)+'.jpg',frame_face)
                        print(count)
                    except:
                        raise

        cv2.imshow("web_frame",frame)
        if cv2.waitKey(1) == 27:
            break

    vs.release()
    cv2.destroyAllWindows()


In [14]:
webcam("faces_from_webcam_Zeeshan","Zeeshan")

New Directory Created
New Directory Created
(279, 246, 408, 418)
1
(311, 207, 380, 286)
1
(278, 259, 400, 414)
2
(281, 262, 402, 415)
3
(279, 261, 401, 415)
4
(277, 259, 399, 411)
5
(277, 258, 400, 415)
6
(278, 259, 401, 413)
7
(277, 258, 399, 413)
8
(277, 258, 400, 415)
9
(277, 260, 400, 416)
10
(270, 259, 396, 424)
11
(271, 262, 394, 415)
12
(270, 261, 393, 413)
13
(269, 259, 390, 415)
14
(284, 258, 403, 407)
15
(319, 237, 437, 384)
16
(307, 153, 437, 321)
17
(347, 113, 492, 291)
18
(351, 57, 507, 249)
19
(361, 67, 516, 260)
20
(365, 84, 519, 275)
21
(379, 107, 522, 299)
22
(442, 151, 585, 346)
23
(468, 177, 603, 353)
24
(454, 170, 590, 354)
25
(454, 170, 588, 353)
26
(450, 170, 586, 354)
27
(436, 168, 577, 354)
28
(389, 169, 522, 332)
29
(371, 168, 505, 331)
30
(354, 172, 488, 344)
31
(341, 176, 468, 337)
32
(334, 183, 457, 337)
33
(336, 183, 457, 336)
34
(335, 183, 460, 343)
35
(340, 175, 466, 338)
36
(346, 158, 477, 314)
37
(351, 158, 484, 311)
38
(357, 158, 490, 309)
39
(361, 160

In [15]:
webcam("faces_from_webcam_Naved","Naved")

New Directory Created
New Directory Created
(461, 318, 580, 468)
3
(353, 225, 461, 361)
5
(349, 188, 457, 322)
6
(361, 182, 466, 315)
7
(367, 179, 479, 322)
8
(398, 169, 522, 321)
9
(369, 242, 509, 414)
13
(351, 297, 485, 462)
14
(359, 219, 520, 422)
15
(318, 156, 488, 364)
16
(320, 125, 496, 351)
17
(271, 64, 455, 294)
18
(264, 62, 426, 273)
19
(270, 81, 420, 273)
20
(289, 113, 438, 301)
21
(292, 135, 436, 309)
22
(289, 159, 434, 343)
23
(300, 151, 458, 350)
24
(315, 178, 473, 369)
25
(325, 165, 483, 361)
27
(299, 172, 452, 359)
28
(285, 179, 442, 368)
29
(287, 173, 445, 364)
30
(265, 165, 429, 371)
31
(254, 174, 415, 375)
32
(268, 178, 424, 369)
33
(269, 179, 424, 366)
34
(614, 13, 634, 37)
34
(269, 180, 424, 367)
35
(269, 180, 423, 368)
36
(270, 180, 426, 370)
37
(270, 182, 426, 371)
38
(275, 181, 434, 379)
39
(307, 189, 470, 389)
40
(318, 190, 478, 389)
41
(322, 193, 484, 392)
42
(332, 188, 499, 403)
43
(288, 236, 448, 433)
51
(612, 30, 630, 52)
51
(281, 236, 437, 430)
52
(274, 234

In [16]:
def get_embedding(images_path,model):
    all_embedings = list()
    label_name = list()
    for file in os.listdir(images_path):
        for image_file in os.listdir(images_path+'\\'+file):
            file_name,file_extension = os.path.splitext(image_file)
            if(file_extension in ['.png','.jpg']):
                img = load_img(images_path+'\\'+file+'\\'+image_file)
                print("1",img)
                img = img_to_array(img)
                print("2",img)
                img = np.expand_dims(img,axis=0)
                print("3",img)
                img = preprocess_input(img)
                print("4",img)
                img_encode = vgg_out(img)
                print("5",img_encode)
                all_embedings.append(np.squeeze(k.eval(img_encode)).tolist())
                label_name.append(file)
    return np.array(all_embedings),label_name

In [17]:
train_embedings_z, label_name_1 = get_embedding(base_dir+'\\faces_from_webcam_Zeeshan',vgg_out)

1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x206231E76D8>
2 [[[  0. 255.   0.]
  [  3. 255.   0.]
  [  2. 252.   0.]
  ...
  [  6. 250.   4.]
  [  1. 255.   2.]
  [  0. 255.   0.]]

 [[  0. 255.   2.]
  [  1. 255.   1.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  1. 255.   0.]
  [  0. 255.   1.]]

 [[  3. 253.   6.]
  [  2. 255.   4.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  4. 252.   5.]]

 ...

 [[  0. 255.   0.]
  [  0. 255.   0.]
  [  1. 255.   9.]
  ...
  [ 13. 249.  17.]
  [  0. 253.   2.]
  [  1. 255.   0.]]

 [[  0. 255.   0.]
  [  1. 254.   3.]
  [  5. 253.   9.]
  ...
  [  3. 255.  12.]
  [  0. 252.   1.]
  [  4. 254.   0.]]

 [[  0. 255.   0.]
  [  5. 253.   6.]
  [  9. 252.  12.]
  ...
  [  0. 255.   4.]
  [  0. 254.   4.]
  [  7. 253.   2.]]]
3 [[[[  0. 255.   0.]
   [  3. 255.   0.]
   [  2. 252.   0.]
   ...
   [  6. 250.   4.]
   [  1. 255.   2.]
   [  0. 255.   0.]]

  [[  0. 255.   2.]
   [  1. 255.   1.]
   [  

5 Tensor("model_2/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x20624624518>
2 [[[  1. 255.   2.]
  [  1. 254.   5.]
  [  3. 251.   5.]
  ...
  [  4. 252.   8.]
  [  1. 255.   8.]
  [  0. 255.   2.]]

 [[  1. 254.   5.]
  [  0. 253.   2.]
  [  0. 254.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   4.]
  [  0. 255.   5.]]

 [[  0. 254.   8.]
  [  0. 255.   3.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   1.]
  [  4. 254.   6.]]

 ...

 [[  2. 255.   7.]
  [  3. 253.   8.]
  [  4. 251.  10.]
  ...
  [ 11. 249.  13.]
  [  4. 255.   0.]
  [  4. 254.   0.]]

 [[  0. 255.   1.]
  [  1. 254.   6.]
  [  3. 253.   8.]
  ...
  [  3. 253.   5.]
  [  2. 255.   0.]
  [  2. 255.   0.]]

 [[  0. 255.   0.]
  [  0. 255.   3.]
  [  2. 255.   6.]
  ...
  [  0. 255.   0.]
  [  1. 255.   0.]
  [  0. 254.   1.]]]
3 [[[[  1. 255.   2.]
   [  1. 254.   5.]
   [  3. 251.   5.]
   ...
   [  4. 252.   8.]
   [  1. 255.   8.

5 Tensor("model_5/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x20624AB7EF0>
2 [[[  2. 255.   0.]
  [  1. 255.   0.]
  [  0. 254.   0.]
  ...
  [  6. 249.   7.]
  [  3. 254.   3.]
  [  0. 255.   0.]]

 [[  0. 252.   3.]
  [  1. 255.   4.]
  [  0. 255.   1.]
  ...
  [  1. 255.   1.]
  [  4. 254.   6.]
  [  4. 254.   6.]]

 [[  1. 255.   7.]
  [  2. 255.   8.]
  [  0. 255.   4.]
  ...
  [  0. 255.   0.]
  [  1. 251.   3.]
  [  7. 250.  10.]]

 ...

 [[  0. 255.   0.]
  [  1. 255.   1.]
  [  6. 252.   5.]
  ...
  [  6. 250.  12.]
  [  0. 255.   2.]
  [  0. 255.   0.]]

 [[  0. 255.   0.]
  [  0. 254.   4.]
  [  3. 252.  10.]
  ...
  [  0. 252.   7.]
  [  0. 255.   2.]
  [  0. 255.   0.]]

 [[  0. 255.   0.]
  [  0. 255.   6.]
  [  2. 254.  13.]
  ...
  [  0. 255.   5.]
  [  1. 255.   4.]
  [  0. 255.   0.]]]
3 [[[[  2. 255.   0.]
   [  1. 255.   0.]
   [  0. 254.   0.]
   ...
   [  6. 249.   7.]
   [  3. 254.   3.

5 Tensor("model_8/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x20622A45EF0>
2 [[[  0. 255.   0.]
  [  2. 255.   0.]
  [  4. 254.   0.]
  ...
  [  0. 253.   9.]
  [  0. 255.   2.]
  [  0. 255.   0.]]

 [[  1. 254.   3.]
  [  3. 254.   1.]
  [  0. 255.   0.]
  ...
  [  0. 255.   1.]
  [  1. 255.   0.]
  [  8. 255.   0.]]

 [[  4. 251.  10.]
  [  1. 254.   6.]
  [  0. 255.   1.]
  ...
  [  0. 255.   0.]
  [  2. 252.   0.]
  [  9. 250.   0.]]

 ...

 [[  0. 255.   0.]
  [  2. 255.   4.]
  [  1. 254.   6.]
  ...
  [ 15. 248.  17.]
  [  5. 253.   6.]
  [  7. 253.   2.]]

 [[  0. 255.   0.]
  [  4. 255.   4.]
  [  4. 252.   5.]
  ...
  [  1. 254.   6.]
  [  0. 253.   2.]
  [  2. 253.   2.]]

 [[  0. 255.   0.]
  [  5. 254.   2.]
  [  5. 251.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   3.]
  [  0. 254.   2.]]]
3 [[[[  0. 255.   0.]
   [  2. 255.   0.]
   [  4. 254.   0.]
   ...
   [  0. 253.   9.]
   [  0. 255.   2.

5 Tensor("model_11/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x20632ED1EB8>
2 [[[  0. 255.  12.]
  [  0. 255.   0.]
  [  4. 255.   0.]
  ...
  [  1. 254.   5.]
  [  0. 255.   0.]
  [  0. 255.   0.]]

 [[  0. 255.  12.]
  [  1. 255.   1.]
  [  4. 255.   0.]
  ...
  [  2. 255.   1.]
  [  0. 255.   1.]
  [  0. 255.   0.]]

 [[  0. 254.  10.]
  [  3. 254.   3.]
  [  4. 254.   0.]
  ...
  [  1. 255.   0.]
  [  4. 250.   0.]
  [  9. 251.   7.]]

 ...

 [[  0. 255.   0.]
  [  1. 254.   3.]
  [  2. 252.   7.]
  ...
  [ 10. 252.  18.]
  [  1. 255.   4.]
  [  2. 255.   0.]]

 [[  0. 255.   0.]
  [  0. 254.   4.]
  [  2. 251.   9.]
  ...
  [  2. 254.  13.]
  [  0. 254.   0.]
  [  0. 255.   0.]]

 [[  0. 255.   0.]
  [  0. 255.   6.]
  [  3. 252.  10.]
  ...
  [  0. 255.  12.]
  [  0. 255.   0.]
  [  0. 255.   0.]]]
3 [[[[  0. 255.  12.]
   [  0. 255.   0.]
   [  4. 255.   0.]
   ...
   [  1. 254.   5.]
   [  0. 255.   0

5 Tensor("model_14/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x20634514C88>
2 [[[  0. 255.   8.]
  [  0. 255.   5.]
  [  0. 255.   3.]
  ...
  [  4. 254.   9.]
  [  0. 254.   4.]
  [  0. 255.   0.]]

 [[  3. 252.  10.]
  [  0. 255.   5.]
  [  0. 255.   0.]
  ...
  [  0. 254.   6.]
  [  0. 254.   5.]
  [  0. 255.   3.]]

 [[ 10. 249.   8.]
  [  0. 254.   0.]
  [  0. 255.   0.]
  ...
  [  6. 253.  12.]
  [  0. 255.   6.]
  [  0. 255.   5.]]

 ...

 [[  5. 255.   0.]
  [  1. 255.   0.]
  [  4. 254.   0.]
  ...
  [ 16. 233.  20.]
  [  4. 252.   6.]
  [  1. 252.   1.]]

 [[  3. 251.   4.]
  [  1. 255.   1.]
  [  0. 254.   0.]
  ...
  [  2. 255.   7.]
  [  1. 255.   5.]
  [  6. 251.   8.]]

 [[  4. 252.  15.]
  [  2. 255.  12.]
  [  0. 255.   5.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  6. 249.   9.]]]
3 [[[[  0. 255.   8.]
   [  0. 255.   5.]
   [  0. 255.   3.]
   ...
   [  4. 254.   9.]
   [  0. 254.   4

5 Tensor("model_17/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2063C5D75C0>
2 [[[  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  4. 252.   8.]
  [  0. 255.   5.]
  [  0. 255.   1.]]

 [[  2. 252.   7.]
  [  0. 255.   3.]
  [  0. 255.   0.]
  ...
  [  0. 255.   2.]
  [  0. 255.   1.]
  [  0. 255.   0.]]

 [[  8. 252.  16.]
  [  0. 255.   7.]
  [  0. 255.   0.]
  ...
  [  1. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   2.]]

 ...

 [[  0. 255.   0.]
  [  0. 255.   0.]
  [  1. 254.   3.]
  ...
  [ 20. 242.   9.]
  [  7. 251.   0.]
  [  2. 254.   0.]]

 [[  0. 255.   0.]
  [  0. 255.   1.]
  [  0. 255.   4.]
  ...
  [  6. 255.   2.]
  [  3. 255.   0.]
  [  4. 255.   4.]]

 [[  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  1. 255.   9.]]]
3 [[[[  0. 255.   0.]
   [  0. 255.   0.]
   [  0. 255.   0.]
   ...
   [  4. 252.   8.]
   [  0. 255.   5

5 Tensor("model_20/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x20704225908>
2 [[[  0. 255.   0.]
  [  0. 255.   0.]
  [  4. 254.   6.]
  ...
  [  0. 255.   3.]
  [  0. 255.   1.]
  [  0. 255.   0.]]

 [[  0. 254.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]

 [[  9. 255.   4.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  1. 255.   1.]
  [  0. 255.   1.]
  [  0. 255.   0.]]

 ...

 [[  4. 252.  16.]
  [  0. 255.   5.]
  [  0. 255.   1.]
  ...
  [ 21. 237.  14.]
  [  6. 249.   9.]
  [  3. 252.  12.]]

 [[  2. 253.  18.]
  [  0. 253.   0.]
  [  0. 255.   0.]
  ...
  [  5. 255.   2.]
  [  1. 255.   2.]
  [  4. 251.  10.]]

 [[  0. 255.  15.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  6. 252.   5.]]]
3 [[[[  0. 255.   0.]
   [  0. 255.   0.]
   [  4. 254.   6.]
   ...
   [  0. 255.   3.]
   [  0. 255.   1

5 Tensor("model_23/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x20705611CF8>
2 [[[  0. 255.   0.]
  [  0. 255.   0.]
  [  6. 253.   0.]
  ...
  [  3. 254.   1.]
  [  1. 255.   0.]
  [  0. 255.   0.]]

 [[  0. 255.   7.]
  [  0. 255.   5.]
  [  1. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  1. 255.   4.]]

 [[  0. 253.  14.]
  [  0. 255.   8.]
  [  0. 255.   1.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  5. 255.   7.]]

 ...

 [[  4. 255.   0.]
  [  4. 255.   2.]
  [  4. 255.   4.]
  ...
  [ 14. 247.  15.]
  [  3. 253.   5.]
  [  0. 255.   5.]]

 [[  0. 255.   0.]
  [  1. 255.   0.]
  [  0. 254.   2.]
  ...
  [  3. 254.   3.]
  [  0. 252.   1.]
  [  1. 255.   7.]]

 [[  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   1.]
  ...
  [  0. 255.   0.]
  [  1. 255.   2.]
  [  0. 254.   6.]]]
3 [[[[  0. 255.   0.]
   [  0. 255.   0.]
   [  6. 253.   0.]
   ...
   [  3. 254.   1.]
   [  1. 255.   0

5 Tensor("model_26/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x207057FC668>
2 [[[  0. 255.   4.]
  [  0. 255.   0.]
  [  4. 255.   0.]
  ...
  [  2. 252.   7.]
  [  1. 255.   7.]
  [  0. 255.   0.]]

 [[  0. 255.   6.]
  [  0. 255.   0.]
  [  1. 255.   0.]
  ...
  [  0. 254.   0.]
  [  2. 255.   4.]
  [  3. 251.   4.]]

 [[  0. 255.  10.]
  [  0. 255.   3.]
  [  1. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 253.   2.]
  [  9. 250.  11.]]

 ...

 [[  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 254.   6.]
  ...
  [  4. 253.  13.]
  [  0. 254.   0.]
  [  0. 255.   0.]]

 [[  0. 255.   0.]
  [  0. 255.   2.]
  [  1. 253.  10.]
  ...
  [  1. 252.   1.]
  [  0. 255.   1.]
  [  1. 255.   3.]]

 [[  0. 255.   0.]
  [  1. 255.   4.]
  [  4. 251.  12.]
  ...
  [  6. 253.   0.]
  [  6. 255.   1.]
  [  0. 251.   0.]]]
3 [[[[  0. 255.   4.]
   [  0. 255.   0.]
   [  4. 255.   0.]
   ...
   [  2. 252.   7.]
   [  1. 255.   7

5 Tensor("model_29/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x20707E4BEF0>
2 [[[  4. 254.   0.]
  [  0. 255.   0.]
  [  0. 255.   5.]
  ...
  [  4. 251.  14.]
  [  0. 255.  10.]
  [  0. 255.   0.]]

 [[  0. 253.   5.]
  [  0. 255.   5.]
  [  0. 255.   5.]
  ...
  [  0. 255.   2.]
  [  0. 255.   6.]
  [  0. 255.   3.]]

 [[  0. 255.  10.]
  [  0. 255.   8.]
  [  0. 255.   3.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  5. 254.   4.]]

 ...

 [[  0. 255.   0.]
  [  1. 255.   0.]
  [  3. 254.   0.]
  ...
  [ 17. 248.  22.]
  [  0. 253.   2.]
  [  1. 255.   0.]]

 [[  0. 255.   4.]
  [  0. 255.   3.]
  [  0. 254.   0.]
  ...
  [  6. 250.  12.]
  [  0. 254.   0.]
  [  0. 255.   0.]]

 [[  0. 255.  12.]
  [  0. 255.   9.]
  [  0. 254.   2.]
  ...
  [  0. 255.   5.]
  [  0. 255.   1.]
  [  0. 255.   0.]]]
3 [[[[  4. 254.   0.]
   [  0. 255.   0.]
   [  0. 255.   5.]
   ...
   [  4. 251.  14.]
   [  0. 255.  10

5 Tensor("model_32/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x20707E09C50>
2 [[[  0. 255.   0.]
  [  0. 255.   0.]
  [  1. 255.   1.]
  ...
  [  1. 252.  14.]
  [  0. 254.  10.]
  [  0. 255.   8.]]

 [[  3. 254.   3.]
  [  1. 254.   5.]
  [  0. 255.   3.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]

 [[  4. 251.  10.]
  [  4. 253.  11.]
  [  0. 255.   5.]
  ...
  [  0. 255.   0.]
  [  1. 255.   0.]
  [  6. 255.   0.]]

 ...

 [[  0. 255.   0.]
  [  0. 255.   1.]
  [  0. 255.   4.]
  ...
  [ 10. 253.  11.]
  [  0. 254.   0.]
  [  0. 255.   0.]]

 [[  1. 254.   3.]
  [  0. 254.   4.]
  [  0. 255.   5.]
  ...
  [  0. 254.   2.]
  [  0. 254.   1.]
  [  0. 255.   5.]]

 [[  9. 251.   6.]
  [  6. 249.   7.]
  [  3. 253.   6.]
  ...
  [  0. 252.   2.]
  [  1. 255.  11.]
  [  0. 253.  12.]]]
3 [[[[  0. 255.   0.]
   [  0. 255.   0.]
   [  1. 255.   1.]
   ...
   [  1. 252.  14.]
   [  0. 254.  10

5 Tensor("model_35/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2070A69EEF0>
2 [[[  0. 255.   0.]
  [  0. 255.   0.]
  [  3. 254.   1.]
  ...
  [  2. 254.  11.]
  [  0. 255.  10.]
  [  0. 255.   4.]]

 [[  0. 255.   1.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]

 [[  6. 251.   6.]
  [  1. 255.   1.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  4. 252.   0.]]

 ...

 [[  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 21. 245.   9.]
  [  6. 253.   0.]
  [  1. 255.   0.]]

 [[  2. 254.   0.]
  [  0. 255.   0.]
  [  0. 255.   1.]
  ...
  [  7. 255.   1.]
  [  2. 253.   0.]
  [  4. 251.  10.]]

 [[  4. 253.   1.]
  [  1. 255.   4.]
  [  0. 255.   7.]
  ...
  [  0. 255.   0.]
  [  0. 253.   3.]
  [  5. 250.  22.]]]
3 [[[[  0. 255.   0.]
   [  0. 255.   0.]
   [  3. 254.   1.]
   ...
   [  2. 254.  11.]
   [  0. 255.  10

5 Tensor("model_38/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2070CCDAEB8>
2 [[[  0. 255.   9.]
  [  0. 255.   2.]
  [  7. 254.   0.]
  ...
  [  0. 254.   0.]
  [  0. 253.   0.]
  [  1. 255.   9.]]

 [[  0. 255.  12.]
  [  1. 255.   2.]
  [  3. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  2. 254.  11.]]

 [[  1. 255.  11.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 253.   5.]]

 ...

 [[  7. 251.   5.]
  [  1. 255.   0.]
  [  3. 255.   0.]
  ...
  [ 24. 231.  19.]
  [  8. 250.   8.]
  [  0. 255.   2.]]

 [[  4. 251.  12.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 15. 250.   8.]
  [  6. 254.   7.]
  [  0. 254.   7.]]

 [[  0. 251.  18.]
  [  0. 255.   1.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   2.]
  [  0. 255.  10.]]]
3 [[[[  0. 255.   9.]
   [  0. 255.   2.]
   [  7. 254.   0.]
   ...
   [  0. 254.   0.]
   [  0. 253.   0

5 Tensor("model_41/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2070F2487F0>
2 [[[  0. 255.   0.]
  [  0. 255.   0.]
  [  1. 255.   0.]
  ...
  [  3. 253.   8.]
  [  0. 253.   4.]
  [  0. 255.   1.]]

 [[  4. 252.   8.]
  [  0. 255.   1.]
  [  0. 255.   0.]
  ...
  [  0. 255.   2.]
  [  0. 255.   0.]
  [  1. 255.   0.]]

 [[ 10. 247.  17.]
  [  0. 255.   5.]
  [  0. 255.   0.]
  ...
  [  3. 253.   5.]
  [  2. 253.   0.]
  [  0. 255.   0.]]

 ...

 [[  6. 252.   1.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 33. 210.  32.]
  [ 18. 244.  23.]
  [  0. 255.   7.]]

 [[  2. 253.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 16. 242.  18.]
  [  3. 247.   9.]
  [  0. 255.   5.]]

 [[  0. 254.   0.]
  [  1. 255.   3.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]]
3 [[[[  0. 255.   0.]
   [  0. 255.   0.]
   [  1. 255.   0.]
   ...
   [  3. 253.   8.]
   [  0. 253.   4

5 Tensor("model_44/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x207116A1320>
2 [[[  0. 255.   0.]
  [  0. 255.   0.]
  [  2. 254.   0.]
  ...
  [  2. 251.  11.]
  [  3. 253.   5.]
  [  3. 255.   0.]]

 [[  0. 254.   6.]
  [  3. 254.   3.]
  [  4. 254.   0.]
  ...
  [  0. 255.   3.]
  [  3. 254.   0.]
  [  8. 253.   0.]]

 [[  1. 253.  12.]
  [  4. 252.   8.]
  [  3. 254.   3.]
  ...
  [  0. 255.   0.]
  [  0. 252.   0.]
  [ 10. 251.   0.]]

 ...

 [[  0. 255.   0.]
  [  0. 255.   1.]
  [  0. 255.   3.]
  ...
  [  8. 255.  10.]
  [  0. 255.   0.]
  [  0. 255.   0.]]

 [[  0. 255.   2.]
  [  0. 255.   4.]
  [  0. 255.   5.]
  ...
  [  0. 252.   7.]
  [  0. 253.   0.]
  [  0. 255.   0.]]

 [[  3. 253.   5.]
  [  3. 253.   6.]
  [  4. 252.   6.]
  ...
  [  3. 255.  14.]
  [  0. 254.   4.]
  [  0. 255.   0.]]]
3 [[[[  0. 255.   0.]
   [  0. 255.   0.]
   [  2. 254.   0.]
   ...
   [  2. 251.  11.]
   [  3. 253.   5

5 Tensor("model_47/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x20712A10EB8>
2 [[[  8. 249.  10.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]

 [[  7. 251.  13.]
  [  0. 255.   3.]
  [  2. 255.   2.]
  ...
  [ 17. 240.  25.]
  [  7. 250.  10.]
  [  0. 255.   0.]]

 [[  0. 255.   9.]
  [  3. 253.   8.]
  [ 20. 242.  19.]
  ...
  [ 41. 197.  51.]
  [ 22. 243.  28.]
  [  0. 255.   0.]]

 ...

 [[  1. 255.   9.]
  [  5. 247.  12.]
  [ 27. 227.  32.]
  ...
  [  2.  96.   2.]
  [ 31. 229.  28.]
  [  0. 255.   0.]]

 [[  1. 250.  10.]
  [  1. 255.   7.]
  [ 14. 255.  16.]
  ...
  [ 15. 194.  15.]
  [ 20. 245.  19.]
  [  0. 255.   0.]]

 [[  4. 253.  11.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  3. 255.   5.]
  [  2. 253.   2.]
  [  0. 255.   0.]]]
3 [[[[  8. 249.  10.]
   [  0. 255.   0.]
   [  0. 255.   0.]
   ...
   [  0. 255.   0.]
   [  0. 255.   0

5 Tensor("model_50/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x20714E7B0F0>
2 [[[  0. 255.   5.]
  [  1. 254.   3.]
  [  7. 252.   0.]
  ...
  [  4. 252.   6.]
  [  0. 252.   7.]
  [  0. 255.   6.]]

 [[  0. 255.   5.]
  [  0. 255.   0.]
  [  4. 254.   0.]
  ...
  [ 11. 249.   5.]
  [  5. 251.   2.]
  [  0. 255.   0.]]

 [[  1. 254.   6.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 24. 240.  17.]
  [  9. 252.   2.]
  [  0. 255.   0.]]

 ...

 [[  8. 250.   5.]
  [  0. 255.   2.]
  [  3. 252.  12.]
  ...
  [ 15. 172.  23.]
  [ 18. 239.  24.]
  [  0. 255.   0.]]

 [[  0. 254.   1.]
  [  0. 255.   2.]
  [  5. 253.   6.]
  ...
  [ 23. 237.  27.]
  [ 10. 253.  15.]
  [  0. 255.   0.]]

 [[  0. 255.   0.]
  [  0. 255.   0.]
  [  1. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]]
3 [[[[  0. 255.   5.]
   [  1. 254.   3.]
   [  7. 252.   0.]
   ...
   [  4. 252.   6.]
   [  0. 252.   7

5 Tensor("model_53/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x207164284A8>
2 [[[  0. 255.   0.]
  [  2. 255.   7.]
  [  3. 254.  17.]
  ...
  [  0. 255.   2.]
  [  4. 252.   5.]
  [  7. 252.   0.]]

 [[  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 254.   6.]
  ...
  [  8. 251.  13.]
  [  4. 253.   3.]
  [  0. 255.   0.]]

 [[  0. 255.   2.]
  [  0. 255.   0.]
  [  3. 252.   2.]
  ...
  [ 29. 232.  29.]
  [ 11. 250.   9.]
  [  0. 255.   0.]]

 ...

 [[  0. 255.   2.]
  [  0. 255.   0.]
  [ 14. 243.   3.]
  ...
  [ 12. 144.  24.]
  [ 19. 235.  27.]
  [  0. 255.   0.]]

 [[  0. 255.   5.]
  [  2. 255.   0.]
  [ 11. 255.   1.]
  ...
  [ 23. 235.  28.]
  [ 12. 255.  17.]
  [  0. 255.   0.]]

 [[  0. 252.   4.]
  [  0. 253.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]]
3 [[[[  0. 255.   0.]
   [  2. 255.   7.]
   [  3. 254.  17.]
   ...
   [  0. 255.   2.]
   [  4. 252.   5

5 Tensor("model_56/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x207187B6EF0>
2 [[[  4. 255.   4.]
  [  5. 251.   0.]
  [  3. 253.   0.]
  ...
  [  0. 255.   8.]
  [  1. 255.   7.]
  [  0. 255.   0.]]

 [[  0. 255.   1.]
  [  0. 255.   0.]
  [  1. 255.   0.]
  ...
  [  7. 249.  14.]
  [  0. 255.   3.]
  [  0. 255.   0.]]

 [[  0. 255.   3.]
  [  0. 255.   1.]
  [  4. 254.   7.]
  ...
  [ 29. 237.  31.]
  [  8. 253.  10.]
  [  0. 255.   0.]]

 ...

 [[  0. 255.  14.]
  [  0. 255.   4.]
  [ 13. 241.   8.]
  ...
  [ 38. 165.  36.]
  [ 21. 233.  24.]
  [  0. 255.   0.]]

 [[  0. 255.  10.]
  [  0. 255.   0.]
  [  9. 254.   1.]
  ...
  [ 32. 235.  31.]
  [ 14. 252.  16.]
  [  0. 255.   0.]]

 [[  0. 255.   6.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]]
3 [[[[  4. 255.   4.]
   [  5. 251.   0.]
   [  3. 253.   0.]
   ...
   [  0. 255.   8.]
   [  1. 255.   7

5 Tensor("model_59/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x20718B770B8>
2 [[[  3. 254.   1.]
  [  3. 254.   3.]
  [  1. 254.   3.]
  ...
  [  0. 255.   5.]
  [  0. 255.   3.]
  [  0. 255.   1.]]

 [[  7. 251.   3.]
  [  1. 254.   3.]
  [  0. 255.   0.]
  ...
  [  0. 254.   4.]
  [  0. 255.   0.]
  [  0. 255.   0.]]

 [[  8. 250.   5.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 11. 247.  14.]
  [  1. 254.   5.]
  [  0. 255.   0.]]

 ...

 [[  2. 252.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 36. 210.  37.]
  [ 15. 246.  18.]
  [  0. 255.   0.]]

 [[  1. 255.   1.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 19. 246.  19.]
  [  5. 250.   9.]
  [  0. 252.   0.]]

 [[  1. 254.   6.]
  [  0. 255.   5.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  3. 255.   8.]]]
3 [[[[  3. 254.   1.]
   [  3. 254.   3.]
   [  1. 254.   3.]
   ...
   [  0. 255.   5.]
   [  0. 255.   3

5 Tensor("model_62/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2071C14D1D0>
2 [[[  0. 253.  15.]
  [  1. 254.   6.]
  [  4. 254.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   2.]]

 [[  1. 254.  13.]
  [  0. 255.   1.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   1.]]

 [[  0. 255.   6.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]

 ...

 [[  5. 254.   4.]
  [  0. 255.   0.]
  [  0. 255.   1.]
  ...
  [ 23. 237.  25.]
  [  6. 249.   7.]
  [  2. 253.   2.]]

 [[  3. 254.   1.]
  [  0. 255.   0.]
  [  0. 254.   0.]
  ...
  [  2. 255.   7.]
  [  0. 255.   5.]
  [  3. 252.  10.]]

 [[  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 254.  14.]]]
3 [[[[  0. 253.  15.]
   [  1. 254.   6.]
   [  4. 254.   0.]
   ...
   [  0. 255.   0.]
   [  0. 255.   0

5 Tensor("model_65/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2071C5FA978>
2 [[[  0. 255.   0.]
  [  3. 255.   0.]
  [  4. 253.   1.]
  ...
  [  0. 255.   0.]
  [  0. 255.   3.]
  [  0. 255.   6.]]

 [[  3. 253.   5.]
  [  3. 254.   3.]
  [  0. 255.   1.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]

 [[  6. 250.  12.]
  [  1. 254.   6.]
  [  0. 255.   0.]
  ...
  [  1. 254.   3.]
  [  0. 255.   0.]
  [  3. 255.   0.]]

 ...

 [[  8. 252.   4.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 29. 231.  21.]
  [  9. 249.   4.]
  [  0. 255.   0.]]

 [[  9. 253.   8.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  9. 251.   7.]
  [  6. 255.   1.]
  [  8. 255.   1.]]

 [[  3. 251.   7.]
  [  0. 255.   1.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  6. 251.   0.]]]
3 [[[[  0. 255.   0.]
   [  3. 255.   0.]
   [  4. 253.   1.]
   ...
   [  0. 255.   0.]
   [  0. 255.   3

5 Tensor("model_68/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2071FA5E9B0>
2 [[[  3. 255.   0.]
  [  6. 253.   0.]
  [  7. 254.   0.]
  ...
  [  4. 253.   1.]
  [  0. 255.   0.]
  [  0. 255.   3.]]

 [[  4. 254.   7.]
  [  1. 254.   3.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   3.]]

 [[  5. 254.  14.]
  [  0. 255.   7.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  3. 254.   3.]]

 ...

 [[  0. 254.   7.]
  [  0. 255.   1.]
  [  0. 255.   1.]
  ...
  [ 22. 244.  13.]
  [  8. 254.   7.]
  [  0. 255.   6.]]

 [[  2. 255.  10.]
  [  0. 255.   1.]
  [  0. 255.   0.]
  ...
  [  7. 254.   0.]
  [  3. 253.   0.]
  [  0. 253.   5.]]

 [[  3. 253.   6.]
  [  1. 253.   0.]
  [  6. 255.   0.]
  ...
  [  0. 255.   0.]
  [  1. 255.   0.]
  [  6. 254.   8.]]]
3 [[[[  3. 255.   0.]
   [  6. 253.   0.]
   [  7. 254.   0.]
   ...
   [  4. 253.   1.]
   [  0. 255.   0

5 Tensor("model_71/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x20722070208>
2 [[[  0. 255.   3.]
  [  0. 255.   2.]
  [  8. 253.   2.]
  ...
  [  6. 253.   0.]
  [  0. 255.   0.]
  [  0. 255.   1.]]

 [[  0. 255.   4.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  1. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   4.]]

 [[  2. 255.   7.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  3. 254.   0.]
  [  3. 254.   0.]
  [  1. 254.   3.]]

 ...

 [[  0. 255.   1.]
  [  0. 255.   0.]
  [  0. 255.   1.]
  ...
  [ 19. 239.  19.]
  [  7. 255.  11.]
  [  1. 255.   6.]]

 [[  3. 254.   3.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 254.   2.]
  [  0. 255.   3.]
  [  1. 251.   4.]]

 [[  6. 252.   5.]
  [  1. 255.   1.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  4. 252.   6.]]]
3 [[[[  0. 255.   3.]
   [  0. 255.   2.]
   [  8. 253.   2.]
   ...
   [  6. 253.   0.]
   [  0. 255.   0

5 Tensor("model_74/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2072237ADD8>
2 [[[  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  2. 252.   5.]
  [  0. 255.  10.]
  [  0. 255.  11.]]

 [[  3. 254.   1.]
  [  1. 255.   1.]
  [  0. 255.   0.]
  ...
  [  2. 255.   0.]
  [  0. 254.   4.]
  [  0. 255.   8.]]

 [[  4. 252.   5.]
  [  4. 252.   5.]
  [  0. 255.   1.]
  ...
  [  1. 255.   0.]
  [  2. 252.   0.]
  [  8. 254.   5.]]

 ...

 [[  0. 255.   0.]
  [  1. 254.   3.]
  [  1. 254.   5.]
  ...
  [  9. 252.  20.]
  [  0. 253.   2.]
  [  0. 253.   0.]]

 [[  0. 255.   1.]
  [  0. 255.   6.]
  [  1. 254.   6.]
  ...
  [  5. 254.  14.]
  [  0. 255.   5.]
  [  0. 255.   1.]]

 [[  0. 255.   5.]
  [  0. 255.   8.]
  [  1. 253.   8.]
  ...
  [  2. 252.   5.]
  [  1. 254.   3.]
  [  0. 255.   0.]]]
3 [[[[  0. 255.   0.]
   [  0. 255.   0.]
   [  0. 255.   0.]
   ...
   [  2. 252.   5.]
   [  0. 255.  10

In [18]:
train_embedings_n,label_name_n = get_embedding(base_dir+'\\faces_from_webcam_Naved',vgg_out)

1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x207225E1FD0>
2 [[[  0. 255.   2.]
  [  0. 255.   3.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 254.   0.]]

 [[  4. 253.  11.]
  [  0. 254.   4.]
  [  0. 254.   0.]
  ...
  [  3. 251.   5.]
  [  2. 255.   0.]
  [  0. 255.   0.]]

 [[  9. 250.  15.]
  [  0. 252.   3.]
  [  0. 255.   0.]
  ...
  [ 20. 239.  23.]
  [  8. 251.   3.]
  [  0. 255.   0.]]

 ...

 [[  8. 251.   3.]
  [  0. 255.   0.]
  [  2. 255.   7.]
  ...
  [ 22. 187.  25.]
  [ 22. 242.  12.]
  [  4. 255.   0.]]

 [[  0. 255.   0.]
  [  0. 254.   4.]
  [  3. 251.   7.]
  ...
  [ 21. 245.  24.]
  [ 10. 254.   8.]
  [  0. 254.   0.]]

 [[  0. 255.   0.]
  [  0. 255.   7.]
  [  1. 251.   4.]
  ...
  [  0. 255.   0.]
  [  0. 255.   3.]
  [  0. 255.   7.]]]
3 [[[[  0. 255.   2.]
   [  0. 255.   3.]
   [  0. 255.   0.]
   ...
   [  0. 255.   0.]
   [  0. 255.   0.]
   [  0. 254.   0.]]

  [[  4. 253.  11.]
   [  0. 254.   4.]
   [  

5 Tensor("model_79/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x207174A8F98>
2 [[[  0. 255.   3.]
  [  1. 254.   6.]
  [  4. 249.   4.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]

 [[  0. 254.   4.]
  [  0. 255.   5.]
  [  2. 255.   3.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  2. 253.   0.]]

 [[  0. 252.   9.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  4. 248.  12.]
  [  3. 251.   7.]
  [  6. 251.   6.]]

 ...

 [[ 11. 248.   8.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 48. 242.  50.]
  [ 11. 251.  20.]
  [  0. 255.   8.]]

 [[  5. 252.  11.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  9. 243.   8.]
  [  0. 250.   2.]
  [  0. 255.   2.]]

 [[  0. 254.   7.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  1. 255.   0.]]]
3 [[[[  0. 255.   3.]
   [  1. 254.   6.]
   [  4. 249.   4.]
   ...
   [  0. 255.   0.]
   [  0. 255.   0

5 Tensor("model_82/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2072583A518>
2 [[[  3. 253.   0.]
  [  4. 254.   7.]
  [  5. 252.  15.]
  ...
  [  1. 255.   0.]
  [  0. 255.   0.]
  [  2. 254.  11.]]

 [[  4. 253.   1.]
  [  0. 255.   3.]
  [  0. 255.   3.]
  ...
  [  0. 255.   0.]
  [  0. 254.   0.]
  [  1. 251.   6.]]

 [[  8. 252.   6.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   1.]
  [  2. 255.   8.]]

 ...

 [[  8. 249.  10.]
  [  0. 255.   2.]
  [  0. 255.   2.]
  ...
  [ 40. 243.  37.]
  [ 11. 248.   8.]
  [  2. 255.   0.]]

 [[  7. 252.  11.]
  [  0. 255.   2.]
  [  0. 255.   0.]
  ...
  [  7. 246.   3.]
  [  4. 253.   1.]
  [  4. 255.   4.]]

 [[  3. 251.   5.]
  [  1. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 252.   3.]]]
3 [[[[  3. 253.   0.]
   [  4. 254.   7.]
   [  5. 252.  15.]
   ...
   [  1. 255.   0.]
   [  0. 255.   0

5 Tensor("model_85/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2072B08C5F8>
2 [[[  7. 254.   0.]
  [  3. 252.   2.]
  [  4. 255.   2.]
  ...
  [  0. 255.   6.]
  [  1. 255.   0.]
  [  3. 255.   0.]]

 [[  5. 255.   7.]
  [  0. 255.   2.]
  [  0. 255.   0.]
  ...
  [  2. 252.   5.]
  [  3. 254.   0.]
  [  1. 255.   0.]]

 [[  1. 253.  12.]
  [  0. 255.   2.]
  [  0. 255.   0.]
  ...
  [ 16. 245.  18.]
  [  7. 253.   6.]
  [  0. 255.   0.]]

 ...

 [[  6. 251.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 69. 242.  75.]
  [ 16. 245.  18.]
  [  0. 255.   0.]]

 [[  4. 255.   0.]
  [  0. 255.   0.]
  [  0. 254.   0.]
  ...
  [ 15. 239.  21.]
  [  3. 248.   5.]
  [  0. 255.   0.]]

 [[  0. 255.   0.]
  [  2. 255.   0.]
  [  1. 255.   0.]
  ...
  [  0. 255.   3.]
  [  0. 255.   0.]
  [  0. 255.   0.]]]
3 [[[[  7. 254.   0.]
   [  3. 252.   2.]
   [  4. 255.   2.]
   ...
   [  0. 255.   6.]
   [  1. 255.   0

5 Tensor("model_88/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x20729F31F60>
2 [[[  0. 255.   2.]
  [  2. 255.  10.]
  [  2. 254.  13.]
  ...
  [  0. 254.   0.]
  [  3. 255.   7.]
  [  1. 253.  10.]]

 [[  0. 254.   0.]
  [  0. 254.   2.]
  [  0. 253.   0.]
  ...
  [  2. 253.   0.]
  [  1. 254.   5.]
  [  0. 253.   6.]]

 [[  7. 253.   2.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 17. 249.  15.]
  [  5. 255.   8.]
  [  0. 255.   4.]]

 ...

 [[  2. 254.  11.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 64. 239.  72.]
  [ 13. 243.  20.]
  [  0. 255.   0.]]

 [[  0. 255.  14.]
  [  0. 255.   0.]
  [  0. 252.   0.]
  ...
  [ 16. 239.  24.]
  [  2. 249.  10.]
  [  0. 255.   2.]]

 [[  0. 255.   9.]
  [  0. 255.   3.]
  [  4. 255.   0.]
  ...
  [  0. 255.   4.]
  [  0. 255.   2.]
  [  0. 255.   0.]]]
3 [[[[  0. 255.   2.]
   [  2. 255.  10.]
   [  2. 254.  13.]
   ...
   [  0. 254.   0.]
   [  3. 255.   7

5 Tensor("model_91/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2072E85E898>
2 [[[  0. 252.   4.]
  [  2. 254.  11.]
  [  5. 252.  11.]
  ...
  [  0. 254.   8.]
  [  3. 255.   7.]
  [  0. 253.   2.]]

 [[  2. 255.   3.]
  [  0. 255.   2.]
  [  0. 255.   0.]
  ...
  [  0. 253.   3.]
  [  0. 255.   3.]
  [  1. 255.   2.]]

 [[  0. 254.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  7. 250.  10.]
  [  1. 254.   3.]
  [  0. 255.   0.]]

 ...

 [[  1. 254.   6.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 60. 241.  64.]
  [ 15. 246.  18.]
  [  0. 255.   0.]]

 [[  6. 254.   8.]
  [  0. 254.   1.]
  [  0. 254.   0.]
  ...
  [ 12. 241.  16.]
  [  2. 250.   4.]
  [  0. 255.   0.]]

 [[  7. 251.   5.]
  [  4. 253.   3.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]]
3 [[[[  0. 252.   4.]
   [  2. 254.  11.]
   [  5. 252.  11.]
   ...
   [  0. 254.   8.]
   [  3. 255.   7

5 Tensor("model_94/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2072E7C9C88>
2 [[[  0. 255.   5.]
  [  0. 253.   3.]
  [  0. 254.   0.]
  ...
  [  0. 255.  11.]
  [  1. 253.   8.]
  [  2. 252.   4.]]

 [[  1. 255.   9.]
  [  0. 255.   8.]
  [  0. 255.   0.]
  ...
  [  3. 251.   7.]
  [  4. 253.   1.]
  [  5. 255.   0.]]

 [[  1. 251.   6.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 17. 244.  17.]
  [  8. 251.   0.]
  [  2. 255.   0.]]

 ...

 [[  5. 251.   2.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 31. 197.  27.]
  [ 17. 242.  16.]
  [  0. 255.   0.]]

 [[  5. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 21. 243.  20.]
  [  7. 252.   7.]
  [  0. 255.   0.]]

 [[  4. 254.   0.]
  [  4. 255.   4.]
  [  0. 255.   2.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]]
3 [[[[  0. 255.   5.]
   [  0. 253.   3.]
   [  0. 254.   0.]
   ...
   [  0. 255.  11.]
   [  1. 253.   8

5 Tensor("model_97/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2072E83A828>
2 [[[  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 254.   0.]
  ...
  [  2. 255.   2.]
  [  2. 252.   0.]
  [  4. 255.   0.]]

 [[  0. 255.   0.]
  [  0. 255.   0.]
  [  1. 255.   0.]
  ...
  [ 11. 249.  13.]
  [  2. 255.   4.]
  [  0. 255.   0.]]

 [[  0. 255.   0.]
  [  0. 255.   0.]
  [  3. 253.   5.]
  ...
  [ 30. 232.  34.]
  [  6. 253.  12.]
  [  0. 255.   0.]]

 ...

 [[  0. 255.   6.]
  [  0. 255.   0.]
  [ 13. 247.  12.]
  ...
  [ 51. 175.  41.]
  [ 23. 237.  17.]
  [  0. 255.   0.]]

 [[  0. 255.   5.]
  [  0. 253.   0.]
  [ 13. 251.   7.]
  ...
  [ 22. 229.  25.]
  [  8. 247.   8.]
  [  0. 255.   0.]]

 [[  0. 255.   7.]
  [  4. 255.   0.]
  [  8. 252.   0.]
  ...
  [  0. 255.   3.]
  [  0. 255.   3.]
  [  0. 255.   0.]]]
3 [[[[  0. 255.   0.]
   [  0. 255.   0.]
   [  0. 254.   0.]
   ...
   [  2. 255.   2.]
   [  2. 252.   0

5 Tensor("model_100/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x207334697F0>
2 [[[  0. 255.   6.]
  [  0. 255.   2.]
  [  2. 255.   4.]
  ...
  [  0. 255.   0.]
  [  1. 255.   0.]
  [  5. 251.   2.]]

 [[  3. 255.   9.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 254.   0.]]

 [[  6. 255.   3.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  1. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   4.]]

 ...

 [[  1. 254.  13.]
  [  0. 255.   6.]
  [  0. 255.   5.]
  ...
  [ 30. 231.  31.]
  [  7. 250.  10.]
  [  0. 255.   1.]]

 [[  1. 254.   5.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 12. 251.  12.]
  [  3. 254.   1.]
  [  3. 254.   0.]]

 [[  6. 253.   0.]
  [  2. 255.   0.]
  [  2. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  7. 254.   0.]]]
3 [[[[  0. 255.   6.]
   [  0. 255.   2.]
   [  2. 255.   4.]
   ...
   [  0. 255.   0.]
   [  1. 255.   

5 Tensor("model_103/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x20736B334E0>
2 [[[  0. 255.   6.]
  [  0. 252.   9.]
  [  6. 251.  10.]
  ...
  [  0. 255.   4.]
  [  0. 254.   4.]
  [  1. 255.   7.]]

 [[  0. 255.   6.]
  [  0. 255.   3.]
  [  0. 253.   0.]
  ...
  [  1. 255.   2.]
  [  0. 254.   0.]
  [  0. 255.   1.]]

 [[  2. 253.   2.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 13. 247.  10.]
  [  4. 250.   0.]
  [  0. 255.   0.]]

 ...

 [[  3. 254.   3.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 37. 217.  32.]
  [ 11. 245.  10.]
  [  0. 255.   0.]]

 [[  4. 255.   4.]
  [  0. 254.   0.]
  [  0. 253.   0.]
  ...
  [ 19. 247.  14.]
  [  8. 252.   6.]
  [  0. 255.   0.]]

 [[  2. 252.   5.]
  [  2. 255.   7.]
  [  0. 255.   7.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  3. 255.   5.]]]
3 [[[[  0. 255.   6.]
   [  0. 252.   9.]
   [  6. 251.  10.]
   ...
   [  0. 255.   4.]
   [  0. 254.   

5 Tensor("model_106/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x20739288A20>
2 [[[  0. 255.   2.]
  [  2. 255.   2.]
  [  8. 253.   2.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]

 [[  0. 255.   5.]
  [  0. 255.   1.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   5.]
  [  0. 255.   7.]]

 [[  3. 255.  10.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  1. 249.  12.]
  [  0. 251.  12.]
  [  1. 252.  14.]]

 ...

 [[  8. 252.  17.]
  [  0. 255.   7.]
  [  0. 255.   4.]
  ...
  [ 31. 221.  27.]
  [ 11. 247.  14.]
  [  0. 255.   1.]]

 [[  6. 250.  12.]
  [  0. 253.   2.]
  [  0. 255.   0.]
  ...
  [ 16. 248.  12.]
  [  5. 254.   2.]
  [  0. 255.   0.]]

 [[  3. 251.   4.]
  [  1. 255.   0.]
  [  1. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]]
3 [[[[  0. 255.   2.]
   [  2. 255.   2.]
   [  8. 253.   2.]
   ...
   [  0. 255.   0.]
   [  0. 255.   

5 Tensor("model_109/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2073A544860>
2 [[[  0. 255.   0.]
  [  0. 255.   1.]
  [  6. 251.   6.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  3. 254.   0.]]

 [[  0. 255.   6.]
  [  3. 255.   5.]
  [  7. 253.   2.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]

 [[  2. 249.   8.]
  [  4. 255.   2.]
  [  4. 254.   0.]
  ...
  [  9. 250.  15.]
  [  4. 254.   6.]
  [  0. 255.   0.]]

 ...

 [[  2. 252.   5.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 33. 218.  39.]
  [ 11. 246.  21.]
  [  0. 255.   3.]]

 [[  5. 253.   6.]
  [  0. 255.   1.]
  [  0. 255.   1.]
  ...
  [ 14. 245.  19.]
  [  5. 255.   8.]
  [  0. 255.   0.]]

 [[  6. 250.   2.]
  [  4. 253.   1.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]]
3 [[[[  0. 255.   0.]
   [  0. 255.   1.]
   [  6. 251.   6.]
   ...
   [  0. 255.   0.]
   [  0. 255.   

5 Tensor("model_112/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2073C7AF358>
2 [[[  0. 255.   0.]
  [  6. 255.   0.]
  [  8. 254.   0.]
  ...
  [  0. 255.   1.]
  [  0. 255.   2.]
  [  0. 255.   5.]]

 [[  0. 255.   0.]
  [  0. 255.   0.]
  [  1. 253.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   4.]]

 [[  2. 255.   6.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  7. 251.   6.]
  [  1. 254.   5.]
  [  0. 255.   2.]]

 ...

 [[  3. 251.   5.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 53. 237.  55.]
  [ 18. 244.  20.]
  [  1. 254.   3.]]

 [[  8. 252.   7.]
  [  3. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 12. 244.  12.]
  [  3. 252.   2.]
  [  0. 255.   0.]]

 [[  9. 247.   3.]
  [  8. 253.   0.]
  [  1. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]]
3 [[[[  0. 255.   0.]
   [  6. 255.   0.]
   [  8. 254.   0.]
   ...
   [  0. 255.   1.]
   [  0. 255.   

5 Tensor("model_115/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2073FE77C88>
2 [[[  0. 255.   0.]
  [  3. 254.   0.]
  [  3. 253.   6.]
  ...
  [  0. 255.   0.]
  [  7. 254.   0.]
  [ 11. 250.   0.]]

 [[  4. 254.   0.]
  [  3. 254.   1.]
  [  0. 255.   1.]
  ...
  [  0. 255.   2.]
  [  0. 255.   3.]
  [  3. 251.   4.]]

 [[  6. 250.   5.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  2. 253.  15.]
  [  0. 255.  10.]
  [  0. 255.   4.]]

 ...

 [[  8. 251.   9.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 48. 239.  47.]
  [ 11. 248.  12.]
  [  0. 255.   0.]]

 [[  6. 251.  10.]
  [  0. 255.   3.]
  [  0. 255.   0.]
  ...
  [ 10. 244.   9.]
  [  1. 251.   4.]
  [  0. 255.   6.]]

 [[  2. 252.   7.]
  [  2. 255.   6.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   5.]]]
3 [[[[  0. 255.   0.]
   [  3. 254.   0.]
   [  3. 253.   6.]
   ...
   [  0. 255.   0.]
   [  7. 254.   

5 Tensor("model_118/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x207411D5A90>
2 [[[  0. 255.   0.]
  [  6. 255.   5.]
  [ 12. 247.   7.]
  ...
  [  0. 255.   4.]
  [  1. 255.   0.]
  [  6. 251.   0.]]

 [[  0. 255.   4.]
  [  1. 255.   4.]
  [  2. 251.   0.]
  ...
  [  0. 255.   2.]
  [  1. 255.   1.]
  [  7. 252.   0.]]

 [[  0. 255.  12.]
  [  0. 255.   1.]
  [  0. 255.   0.]
  ...
  [  6. 250.  12.]
  [  5. 253.   6.]
  [  6. 253.   0.]]

 ...

 [[  7. 249.  14.]
  [  0. 255.   5.]
  [  0. 255.   2.]
  ...
  [ 51. 239.  57.]
  [ 12. 248.  18.]
  [  0. 255.   1.]]

 [[  8. 252.   6.]
  [  1. 255.   0.]
  [  0. 255.   0.]
  ...
  [  9. 241.  15.]
  [  0. 251.   3.]
  [  0. 255.   0.]]

 [[  5. 253.   0.]
  [  3. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]]
3 [[[[  0. 255.   0.]
   [  6. 255.   5.]
   [ 12. 247.   7.]
   ...
   [  0. 255.   4.]
   [  1. 255.   

5 Tensor("model_121/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x207411371D0>
2 [[[  0. 254.   2.]
  [  1. 255.   2.]
  [  3. 255.   1.]
  ...
  [  1. 254.   3.]
  [  3. 252.   0.]
  [  7. 254.   0.]]

 [[  7. 252.   9.]
  [  1. 254.   3.]
  [  0. 255.   0.]
  ...
  [  4. 252.   5.]
  [  3. 252.   0.]
  [  2. 255.   0.]]

 [[ 11. 250.  11.]
  [  0. 255.   1.]
  [  0. 255.   0.]
  ...
  [ 15. 245.  14.]
  [  4. 254.   6.]
  [  0. 255.   0.]]

 ...

 [[  6. 252.   3.]
  [  0. 255.   0.]
  [  0. 255.   2.]
  ...
  [ 32. 208.  45.]
  [ 14. 245.  25.]
  [  0. 255.   0.]]

 [[  0. 254.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 14. 245.  25.]
  [  8. 251.   9.]
  [  1. 253.   0.]]

 [[  1. 255.   0.]
  [  3. 255.   1.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  1. 255.   0.]
  [ 12. 253.   0.]]]
3 [[[[  0. 254.   2.]
   [  1. 255.   2.]
   [  3. 255.   1.]
   ...
   [  1. 254.   3.]
   [  3. 252.   

5 Tensor("model_124/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x207449047B8>
2 [[[  0. 255.   1.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  7. 249.   4.]
  [  8. 252.   4.]
  [  0. 253.   4.]]

 [[  0. 255.   3.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  4. 254.   0.]
  [  7. 255.   1.]
  [  1. 255.   1.]]

 [[  4. 252.   6.]
  [  3. 254.   3.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  1. 255.   0.]
  [  0. 253.   0.]]

 ...

 [[  3. 253.   5.]
  [  4. 254.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   2.]
  [  0. 255.   2.]
  [  0. 252.   9.]]

 [[  2. 253.   2.]
  [  2. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   5.]
  [  4. 254.   9.]]

 [[  1. 255.   1.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   2.]
  [  1. 255.   1.]
  [  4. 250.   3.]]]
3 [[[[  0. 255.   1.]
   [  0. 255.   0.]
   [  0. 255.   0.]
   ...
   [  7. 249.   4.]
   [  8. 252.   

5 Tensor("model_127/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x20747F7F828>
2 [[[  0. 255.   2.]
  [  0. 255.   0.]
  [  2. 254.   0.]
  ...
  [  0. 255.   0.]
  [  2. 255.   0.]
  [  9. 253.   0.]]

 [[  2. 255.   7.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   4.]
  [  1. 255.   0.]
  [  4. 251.   0.]]

 [[  3. 250.   9.]
  [  1. 255.   1.]
  [  0. 255.   0.]
  ...
  [ 10. 251.  14.]
  [  5. 255.   5.]
  [  0. 254.   0.]]

 ...

 [[  9. 252.  10.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 24. 210.  21.]
  [ 14. 247.  15.]
  [  0. 255.   0.]]

 [[ 11. 251.   6.]
  [  0. 254.   0.]
  [  0. 255.   0.]
  ...
  [ 16. 247.  19.]
  [  3. 253.   5.]
  [  0. 255.   0.]]

 [[ 11. 250.   1.]
  [  4. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   1.]
  [  0. 255.   0.]]]
3 [[[[  0. 255.   2.]
   [  0. 255.   0.]
   [  2. 254.   0.]
   ...
   [  0. 255.   0.]
   [  2. 255.   

5 Tensor("model_130/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2074806DF98>
2 [[[  6. 253.   0.]
  [  2. 254.   0.]
  [  1. 255.   0.]
  ...
  [  1. 252.  15.]
  [  2. 251.   9.]
  [  4. 255.   4.]]

 [[  7. 253.   4.]
  [  0. 255.   1.]
  [  0. 255.   0.]
  ...
  [  7. 250.   8.]
  [  6. 253.   0.]
  [  2. 255.   0.]]

 [[  8. 253.  10.]
  [  0. 254.   0.]
  [  0. 255.   0.]
  ...
  [ 22. 244.  13.]
  [  7. 254.   0.]
  [  0. 255.   0.]]

 ...

 [[  5. 255.   1.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 64. 230.  62.]
  [ 20. 245.  19.]
  [  0. 255.   0.]]

 [[  3. 255.   3.]
  [  0. 254.   0.]
  [  0. 254.   0.]
  ...
  [ 16. 242.  20.]
  [  5. 249.   4.]
  [  0. 255.   0.]]

 [[  1. 251.   3.]
  [  5. 254.   4.]
  [  1. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]]
3 [[[[  6. 253.   0.]
   [  2. 254.   0.]
   [  1. 255.   0.]
   ...
   [  1. 252.  15.]
   [  2. 251.   

5 Tensor("model_133/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x207493A16D8>
2 [[[  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 252.   3.]
  ...
  [  2. 255.   6.]
  [  2. 255.   2.]
  [  3. 254.   0.]]

 [[  0. 254.   0.]
  [  0. 255.   0.]
  [  0. 255.   1.]
  ...
  [  0. 255.   0.]
  [  0. 253.   1.]
  [  5. 251.   2.]]

 [[  8. 254.   7.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   3.]
  [  0. 255.   5.]
  [  8. 253.   8.]]

 ...

 [[  0. 253.  15.]
  [  0. 255.   6.]
  [  0. 254.   4.]
  ...
  [ 15. 248.  19.]
  [  0. 254.   4.]
  [  0. 255.   5.]]

 [[  0. 255.  11.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 254.   0.]
  [  2. 255.   1.]
  [  5. 255.   7.]]

 [[  0. 255.   1.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  4. 255.   0.]
  [  9. 248.   0.]]]
3 [[[[  0. 255.   0.]
   [  0. 255.   0.]
   [  0. 252.   3.]
   ...
   [  2. 255.   6.]
   [  2. 255.   

5 Tensor("model_136/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2074CE50AC8>
2 [[[  0. 255.   0.]
  [  1. 255.   0.]
  [  3. 254.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   8.]]

 [[  0. 254.  10.]
  [  0. 255.   2.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   8.]]

 [[  0. 253.  19.]
  [  0. 255.   9.]
  [  0. 255.   0.]
  ...
  [  3. 253.   0.]
  [  0. 255.   0.]
  [  0. 255.   5.]]

 ...

 [[  2. 251.  11.]
  [  0. 255.   4.]
  [  2. 255.   7.]
  ...
  [ 33. 241.  33.]
  [  9. 250.  11.]
  [  0. 255.   5.]]

 [[  0. 255.   2.]
  [  0. 255.   0.]
  [  1. 255.   0.]
  ...
  [  4. 250.   3.]
  [  0. 255.   5.]
  [  0. 254.   8.]]

 [[  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  1. 255.   9.]]]
3 [[[[  0. 255.   0.]
   [  1. 255.   0.]
   [  3. 254.   0.]
   ...
   [  0. 255.   0.]
   [  0. 255.   

5 Tensor("model_139/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x20750426048>
2 [[[  0. 255.   0.]
  [  0. 255.   5.]
  [  3. 253.   5.]
  ...
  [  0. 255.   7.]
  [  3. 254.   3.]
  [ 10. 250.   1.]]

 [[  1. 255.   3.]
  [  2. 255.   1.]
  [  1. 255.   0.]
  ...
  [  0. 255.   2.]
  [  0. 255.   1.]
  [  7. 253.   6.]]

 [[  4. 250.   1.]
  [  0. 254.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   7.]
  [  0. 255.   2.]
  [  0. 254.   4.]]

 ...

 [[  0. 254.   4.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 42. 242.  48.]
  [  8. 249.  14.]
  [  0. 255.   1.]]

 [[  2. 255.   6.]
  [  0. 255.   1.]
  [  0. 255.   0.]
  ...
  [  7. 248.  13.]
  [  2. 252.   7.]
  [  2. 255.   7.]]

 [[  2. 253.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 253.   5.]]]
3 [[[[  0. 255.   0.]
   [  0. 255.   5.]
   [  3. 253.   5.]
   ...
   [  0. 255.   7.]
   [  3. 254.   

5 Tensor("model_142/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x207517ACDD8>
2 [[[  0. 255.   3.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  9. 249.   2.]
  [  5. 254.   2.]
  [  0. 255.   0.]]

 [[  4. 254.   7.]
  [  4. 255.   4.]
  [  1. 254.   3.]
  ...
  [  3. 255.   0.]
  [  2. 255.   0.]
  [  0. 255.   1.]]

 [[  7. 249.   5.]
  [  6. 250.   5.]
  [  4. 252.   5.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   2.]]

 ...

 [[  0. 254.   6.]
  [  2. 255.   6.]
  [  0. 254.   0.]
  ...
  [  4. 252.   6.]
  [  0. 252.   4.]
  [  2. 252.   7.]]

 [[  3. 252.   2.]
  [  3. 255.   3.]
  [  1. 255.   0.]
  ...
  [  3. 253.   5.]
  [  1. 254.   6.]
  [  2. 255.  10.]]

 [[  4. 254.   0.]
  [  1. 255.   0.]
  [  0. 255.   0.]
  ...
  [  1. 255.   1.]
  [  0. 254.   4.]
  [  0. 255.   6.]]]
3 [[[[  0. 255.   3.]
   [  0. 255.   0.]
   [  0. 255.   0.]
   ...
   [  9. 249.   2.]
   [  5. 254.   

5 Tensor("model_145/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x20753C9DE10>
2 [[[  0. 255.   2.]
  [  0. 255.   3.]
  [  2. 255.   5.]
  ...
  [  0. 252.   3.]
  [  0. 252.   6.]
  [  0. 255.  13.]]

 [[  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   2.]
  ...
  [  5. 251.   2.]
  [  0. 254.   0.]
  [  0. 255.   0.]]

 [[  1. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 23. 246.  17.]
  [  4. 255.   0.]
  [  0. 255.   0.]]

 ...

 [[  1. 254.   3.]
  [  0. 255.   0.]
  [  0. 255.   6.]
  ...
  [ 33. 191.  34.]
  [ 22. 237.  20.]
  [  1. 255.   0.]]

 [[  2. 255.   5.]
  [  0. 255.   0.]
  [  0. 255.   3.]
  ...
  [ 22. 243.  24.]
  [  9. 252.  12.]
  [  0. 255.   0.]]

 [[  0. 254.   0.]
  [  0. 254.   0.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]]
3 [[[[  0. 255.   2.]
   [  0. 255.   3.]
   [  2. 255.   5.]
   ...
   [  0. 252.   3.]
   [  0. 252.   

5 Tensor("model_148/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x207571FDE80>
2 [[[  1. 255.   1.]
  [ 10. 249.   8.]
  [ 14. 246.  14.]
  ...
  [  2. 253.   0.]
  [  3. 254.   0.]
  [  6. 252.   3.]]

 [[  1. 254.   3.]
  [  4. 252.   5.]
  [  4. 252.   5.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  3. 254.   1.]]

 [[  0. 255.   3.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 254.   1.]
  [  0. 255.   0.]
  [  0. 255.   0.]]

 ...

 [[  7. 254.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 48. 242.  50.]
  [ 12. 249.  19.]
  [  0. 255.   5.]]

 [[  0. 252.  11.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 12. 246.  11.]
  [  3. 253.   5.]
  [  0. 255.   3.]]

 [[  0. 251.  21.]
  [  1. 255.  10.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]]
3 [[[[  1. 255.   1.]
   [ 10. 249.   8.]
   [ 14. 246.  14.]
   ...
   [  2. 253.   0.]
   [  3. 254.   

5 Tensor("model_151/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x20758471828>
2 [[[  0. 255.   5.]
  [  0. 254.   0.]
  [  6. 253.   0.]
  ...
  [  0. 255.   4.]
  [  0. 255.   6.]
  [  0. 255.   8.]]

 [[  0. 255.   9.]
  [  0. 255.   1.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   4.]
  [  0. 255.   7.]]

 [[  3. 252.  10.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  4. 252.   8.]
  [  1. 254.   3.]
  [  0. 255.   0.]]

 ...

 [[  4. 254.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 46. 244.  43.]
  [  7. 252.   7.]
  [  0. 255.   0.]]

 [[  4. 253.   1.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [  9. 248.   9.]
  [  2. 252.   4.]
  [  0. 253.   0.]]

 [[  5. 249.   4.]
  [  8. 254.   5.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 254.   0.]
  [  7. 252.   7.]]]
3 [[[[  0. 255.   5.]
   [  0. 254.   0.]
   [  6. 253.   0.]
   ...
   [  0. 255.   4.]
   [  0. 255.   

5 Tensor("model_154/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2075A987940>
2 [[[  5. 255.   0.]
  [  4. 254.   0.]
  [  1. 255.   0.]
  ...
  [  4. 254.   7.]
  [  3. 253.   5.]
  [  0. 254.   0.]]

 [[  0. 252.   7.]
  [  0. 255.   1.]
  [  0. 255.   0.]
  ...
  [  4. 251.  10.]
  [  0. 255.   0.]
  [  0. 255.   0.]]

 [[  0. 252.  13.]
  [  0. 255.   1.]
  [  0. 255.   0.]
  ...
  [ 17. 243.  22.]
  [  0. 255.   3.]
  [  0. 255.   0.]]

 ...

 [[  5. 250.   7.]
  [  0. 255.   2.]
  [  0. 255.   6.]
  ...
  [ 71. 237.  69.]
  [ 20. 243.  15.]
  [  0. 255.   0.]]

 [[  3. 253.   6.]
  [  0. 255.   2.]
  [  0. 255.   2.]
  ...
  [ 19. 241.  20.]
  [  5. 249.   4.]
  [  0. 255.   0.]]

 [[  4. 252.   5.]
  [  7. 253.   2.]
  [  0. 254.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   0.]
  [  0. 255.   0.]]]
3 [[[[  5. 255.   0.]
   [  4. 254.   0.]
   [  1. 255.   0.]
   ...
   [  4. 254.   7.]
   [  3. 253.   

5 Tensor("model_157/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2075A9CA978>
2 [[[  0. 255.   5.]
  [  0. 253.   0.]
  [  5. 255.   0.]
  ...
  [  0. 254.   2.]
  [  0. 255.   6.]
  [  0. 255.   6.]]

 [[  5. 254.  12.]
  [  0. 253.   2.]
  [  0. 255.   0.]
  ...
  [  3. 251.   5.]
  [  2. 252.   5.]
  [  0. 254.   4.]]

 [[  7. 250.  12.]
  [  1. 255.   2.]
  [  0. 255.   0.]
  ...
  [ 20. 246.  22.]
  [  8. 253.  12.]
  [  0. 255.   2.]]

 ...

 [[  8. 250.   6.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 68. 239.  72.]
  [ 16. 246.  16.]
  [  0. 255.   0.]]

 [[  2. 255.   7.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 17. 239.  18.]
  [  5. 248.   6.]
  [  0. 255.   0.]]

 [[  0. 255.   5.]
  [  0. 255.   2.]
  [  0. 255.   0.]
  ...
  [  0. 255.   0.]
  [  0. 255.   1.]
  [  0. 254.   0.]]]
3 [[[[  0. 255.   5.]
   [  0. 253.   0.]
   [  5. 255.   0.]
   ...
   [  0. 254.   2.]
   [  0. 255.   

5 Tensor("model_160/flatten/Reshape:0", shape=(1, 2622), dtype=float32)
1 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=224x224 at 0x2075E14EA90>
2 [[[  0. 255.   0.]
  [  0. 254.   0.]
  [  0. 254.   0.]
  ...
  [  0. 253.   9.]
  [  8. 253.  10.]
  [  7. 249.   4.]]

 [[  4. 253.   1.]
  [  1. 255.   0.]
  [  0. 255.   0.]
  ...
  [  0. 252.   7.]
  [  4. 254.   6.]
  [  3. 253.   0.]]

 [[  9. 251.   9.]
  [  2. 255.   1.]
  [  0. 255.   0.]
  ...
  [ 12. 250.  17.]
  [  3. 255.   7.]
  [  0. 255.   0.]]

 ...

 [[ 10. 250.   3.]
  [  0. 255.   0.]
  [  0. 255.   0.]
  ...
  [ 60. 242.  62.]
  [ 14. 244.  11.]
  [  0. 255.   0.]]

 [[  4. 254.   7.]
  [  0. 254.   0.]
  [  0. 255.   0.]
  ...
  [ 15. 241.  17.]
  [  3. 251.   5.]
  [  0. 255.   0.]]

 [[  0. 254.   7.]
  [  1. 254.   6.]
  [  2. 255.   5.]
  ...
  [  0. 255.   1.]
  [  0. 255.   4.]
  [  0. 255.   1.]]]
3 [[[[  0. 255.   0.]
   [  0. 254.   0.]
   [  0. 254.   0.]
   ...
   [  0. 253.   9.]
   [  8. 253.  1

5 Tensor("model_163/flatten/Reshape:0", shape=(1, 2622), dtype=float32)


In [20]:
df = np.append(train_embedings_z,train_embedings_n,axis=0)
label = label_name_1 + label_name_n

In [21]:
import pandas as pd

In [22]:
df = pd.DataFrame(df)
df['label'] = label

In [23]:
df.head()

0         1         2         3         4         5         6  \
0  3.257433  1.988827  0.999619  0.868316  0.914832  1.260000  0.731888   
1  3.459348  2.394210  1.544606  1.152801  1.007585  1.332297  1.224643   
2  2.384485  2.342943  1.637228  2.589442  2.442425  1.691821  1.715432   
3  3.687497  2.380669  1.227559  0.869837  1.000654  1.530134  1.016484   
4  3.399204  2.306030  1.257263  0.905320  0.836378  1.624975  1.105924   

          7         8         9  ...      2613      2614      2615      2616  \
0  1.782274  1.905770  1.368381  ... -2.085605 -1.989473  0.938217 -0.040602   
1  1.725598  2.281986  1.539851  ... -2.327751 -2.131411  0.625309  0.501266   
2  2.265785  2.932995  2.721998  ... -1.332198 -0.843499  1.086236  0.920398   
3  1.597574  2.090693  1.778401  ... -2.237745 -2.422377  1.028618  0.352166   
4  2.000994  2.018872  1.461685  ... -2.144931 -2.214689  0.598119  0.067725   

       2617      2618      2619      2620      2621    label  
0  0.001493 -1.380632 -0.996122  0.658205  2.124076  Zeeshan  
1  0.188712 -1.349057 -0.626534  0.932405  2.473026  Zeeshan  
2 -0.739426 -1.760012 -0.599162  2.465844  2.519948  Zeeshan  
3  0.319735 -1.420694 -0.952504  1.075890  2.644857  Zeeshan  
4  0.634952 -1.523190 -0.610928  0.940639  2.424738  Zeeshan  

[5 rows x 2623 columns]

In [24]:
from sklearn.utils import shuffle

In [25]:
df_shuf = shuffle(df)

In [26]:
df_shuf = shuffle(df)

In [27]:
df_shuf

0         1         2         3         4         5         6  \
24   2.634531  0.886243  0.582506  1.639820 -0.002107  1.814509  1.171276   
123  4.398960  2.599392  1.081618  1.927613  2.723447  2.282273  0.883168   
34   3.131574  1.681163  1.154237  1.294407  0.390199  1.059280  0.802552   
64   2.990419  1.465630  0.817802  1.567986  1.157666  1.449423  0.626656   
46   3.260125  2.345816  1.287984  1.029851  0.416336  0.847893  0.699110   
137  3.963011  3.144407  1.176685  2.059177  2.727493  2.265650  1.128104   
71   2.929642  3.115182  1.691188  1.696388  2.144538  2.058481  1.673153   
68   2.889045  1.173661  1.200426  2.010145  1.070592  1.839947  1.091663   
99   4.723495  4.282933  2.502706  1.919905  3.677420  2.372428  1.464865   
129  5.230564  4.229308  1.104338  0.463171  1.935545  3.058821  2.241401   
38   3.320966  2.456135  1.345572  0.672178  0.652944  1.575972  1.112634   
142  6.027990  3.814232  1.948323  0.750861  3.008883  3.096739  2.491554   
146  3.939750  1.526269 -0.055226  1.933540  1.526150  1.793499 -0.095822   
7    2.341232  1.730893  1.448089  1.290499  0.724736  1.426232  1.474581   
115  2.681948  2.830072  0.911343  2.921750  2.001599  1.788901  1.814210   
85   4.534867  2.456971  1.818339  0.654598  2.298552  2.825840  0.527659   
42   3.206767  2.669844  1.601633  1.292596  1.255087  1.845984  1.184939   
138  5.003979  3.003483  2.094815  0.915306  2.623038  2.910131  1.139514   
45   3.403228  2.524015  1.485366  1.038637  0.248286  1.380053  1.052508   
65   3.320237  2.438072  1.522818  1.319168  1.029588  1.348940  1.212417   
134  4.529850  3.302831  1.222516  1.448279  2.698593  3.107197  1.479531   
22   2.305232  1.834782  1.007726  1.111936  0.772779  1.319103  0.934461   
1    3.459348  2.394210  1.544606  1.152801  1.007585  1.332297  1.224643   
43   3.456575  2.637411  1.048800  0.569139  0.728637  1.951301  1.325618   
104  4.629988  2.089973  0.626088  1.171722  3.071014  2.071110 -0.355030   
30   2.936164  1.803894  1.146502  1.415858  1.760438  2.211408  0.690275   
116  5.062566  2.603606  0.800393  0.830112  2.980386  2.400632 -0.014999   
69   1.616459  2.930367  1.198073  2.269401  1.985820  1.608184  1.813266   
25   2.748190  1.188267  1.278179  1.042178 -0.155494  1.577137  0.770221   
50   3.738784  0.904117  1.351693  2.045319  0.629461  2.061312  0.186874   
..        ...       ...       ...       ...       ...       ...       ...   
108  4.101671  2.909992  0.616157  1.181893  2.609483  2.243127  0.098401   
82   4.948085  2.780080  0.881510  0.629482  3.955371  2.555955  2.639337   
160  4.650420  3.108962  1.265375  0.806057  2.862620  2.732651  0.562912   
157  4.730546  2.270001  1.218982  1.557274  2.600091  2.590188  0.212438   
98   2.943866  4.022756  2.528159  1.946743  3.161800  1.992686  2.160091   
63   3.234606  2.202816  1.576068  1.251351  0.540897  1.984440  1.924945   
58   2.581898  2.195467  0.862603  2.138893  0.920901  1.619805  1.572248   
95   2.766333  4.331985  3.119422  2.005584  3.991871  2.275229  2.850076   
32   3.257065  2.641062  1.190843  2.113583  2.090953  2.964718  1.941329   
67   2.821501  2.480289  1.020946  1.418293  1.123458  1.694801  1.979045   
62   3.339898  2.118943  0.817918  1.639911  1.400824  1.703739  1.406472   
26   2.551282  1.048287  0.819142  0.988632 -0.034837  1.283598  0.680681   
2    2.384485  2.342943  1.637228  2.589442  2.442425  1.691821  1.715432   
79   3.726144  3.979665  2.053865  1.519680  3.349011  1.850149  2.052770   
59   1.884290  2.594074  1.680951  2.327791  2.019397  1.465076  1.838028   
112  4.160244  3.434995  1.883415  0.987119  3.041599  1.722806  1.942454   
41   3.049974  2.051484  1.326098  0.001250  0.556280  1.699313  0.790544   
28   2.741602  1.553335  0.027636  1.259158  0.446580  1.415137  1.171866   
127  2.586796  2.701829  0.990169  2.737355  2.140586  1.711247  2.114399   
87   4.702298  3.155104  1.706846  1.127705  2.338036  2.005961  0.469751   
150  4.2

In [28]:
x = df_shuf.drop(columns = ['label'])
y = df_shuf.label

In [29]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [30]:
# define baseline model
def baseline_model():
    # create model
    #model = Sequential()
    #model.add(Dense(8, input_dim=128, activation='relu'))
    #model.add(Dense(5, activation='softmax'))
    # Compile model
    #model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    classifier_model=Sequential()
    classifier_model.add(Dense(units=200,input_dim=2622))
    classifier_model.add(BatchNormalization())
    classifier_model.add(Activation('relu'))
    classifier_model.add(Dropout(0.3))
    classifier_model.add(Dense(units=10))
    classifier_model.add(BatchNormalization())
    classifier_model.add(Activation('relu'))
    classifier_model.add(Dropout(0.2))
    classifier_model.add(Dense(units=2))
    classifier_model.add(Activation('softmax'))
    classifier_model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
    return classifier_model

In [31]:
classifier_model = baseline_model()

In [32]:
classifier_model

In [33]:
classifier_model.fit(np.array(x),y,epochs = 50, validation_split =0.2,batch_size=5)

Train on 131 samples, validate on 33 samples
Epoch 1/50
131/131 [==============================] - 6s 45ms/sample - loss: 0.3820 - acc: 0.8168 - val_loss: 1.9387 - val_acc: 0.6970
Epoch 2/50
131/131 [==============================] - 0s 2ms/sample - loss: 0.2459 - acc: 0.9313 - val_loss: 0.1288 - val_acc: 0.9394
Epoch 3/50
131/131 [==============================] - 0s 2ms/sample - loss: 0.3868 - acc: 0.8550 - val_loss: 0.0460 - val_acc: 1.0000
Epoch 4/50
131/131 [==============================] - 0s 2ms/sample - loss: 0.1617 - acc: 0.9771 - val_loss: 0.1519 - val_acc: 0.9697
Epoch 5/50
131/131 [==============================] - 0s 3ms/sample - loss: 0.2395 - acc: 0.9389 - val_loss: 0.1287 - val_acc: 0.9697
Epoch 6/50
131/131 [==============================] - 0s 3ms/sample - loss: 0.2165 - acc: 0.9466 - val_loss: 0.0310 - val_acc: 1.0000
Epoch 7/50
131/131 [==============================] - 0s 3ms/sample - loss: 0.2513 - acc: 0.9313 - val_loss: 0.0583 - val_acc: 0.9697
Epoch 8/50
131/1

In [34]:
classifier_model.save('face_recog_cnn_classifier_zee_nav.h5')

In [35]:
np.save('face_recog_cnn_classifier_zee_nav.npy',le.classes_)